# This file was generated by liblab | https://liblab.com/

from .services.shipments import ShipmentsService
from .services.labels import LabelsService
from .net.environment import Environment


class UpsShipping:
    def __init__(
        self,
        username: str = None,
        password: str = None,
        base_url: str = Environment.DEFAULT.value,
    ):
        """
        Initializes UpsShipping the SDK class.
        """
        self.shipments = ShipmentsService(base_url=base_url)
        self.labels = LabelsService(base_url=base_url)
        self.set_basic_auth(username=username, password=password)

    def set_base_url(self, base_url):
        """
        Sets the base URL for the entire SDK.
        """
        self.shipments.set_base_url(base_url)
        self.labels.set_base_url(base_url)

        return self

    def set_basic_auth(self, username: str, password: str):
        """
        Sets the username and password for the entire SDK.
        """
        self.shipments.set_basic_auth(username=username, password=password)
        self.labels.set_basic_auth(username=username, password=password)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
