# This file was generated by liblab | https://liblab.com/

from ups_shipping import UpsShipping, Environment

sdk = UpsShipping(
    username="YOUR_USERNAME",
    password="YOUR_PASSWORD",
    base_url=Environment.DEFAULT.value,
)

result = sdk.shipments.void_shipment(
    version="v2403",
    shipmentidentificationnumber="shipmentidentificationnumber",
    trackingnumber="trackingnumber",
    trans_id="transId",
    transaction_src="testing",
)

print(result)
